export const illustrationImagesData = [
  {
    imageId: "Illustration_39874",
    imageTitle: "Header image for GullyGang NFT collection",
    imageUrl: "/Images/Illustrations/GullyGang_Header.png",
    alt: "Header image for GullyGang NFT collection",
    width: 2133,
    height: 1200,
  },
  {
    imageId: "Illustration_kf948",
    imageTitle: "Seagull illustration for GullyGang NFT collection",
    imageUrl: "/Images/Illustrations/GullyGang_Gull_1.png",
    alt: "Seagull illustration for GullyGang NFT collection",
    width: 1200,
    height: 1200,
  },
  {
    imageId: "Illustration_cka72",
    imageTitle: "Seagull illustration for GullyGang NFT collection",
    imageUrl: "/Images/Illustrations/GullyGang_Gull_2.png",
    alt: "Seagull illustration for GullyGang NFT collection",
    width: 1200,
    height: 1200,
  },
  {
    imageId: "Illustration_bbre6",
    imageTitle: "Seagull illustration for GullyGang NFT collection",
    imageUrl: "/Images/Illustrations/GullyGang_Gull_3.png",
    alt: "Seagull illustration for GullyGang NFT collection",
    width: 1200,
    height: 1200,
  },
  {
    imageId: "Illustration_dho32",
    imageTitle: "Seagull illustrations for GullyGang NFT collection",
    imageUrl: "/Images/Illustrations/GullyGang_Group.png",
    alt: "Seagull illustrations for GullyGang NFT collection",
    width: 1800,
    height: 1200,
  },
  {
    imageId: "Illustration_vafg8",
    imageTitle:
      "Character illustration for packaging of Bio Obst Augustin Hagel Aepfel",
    imageUrl: "/Images/Illustrations/Augustin_Hagel_Aepfel.jpg",
    alt: "Character illustration for packaging of Bio Obst Augustin Hagel Aepfel",
    width: 1147,
    height: 943,
  },
  {
    imageId: "Illustration_ftl66",
    imageTitle: "Illustrations for Douglas Wiesn event invitation",
    imageUrl: "/Images/Illustrations/Douglas_Wiesn_Illustration.jpg",
    alt: "Illustrations for Douglas Wiesn event invitation",
    width: 981,
    height: 987,
  },
  {
    imageId: "Illustration_jlx31",
    imageTitle: "Icon set for Cognac Expert online shop",
    imageUrl: "/Images/Illustrations/CE_Icons.jpg",
    alt: "Icon set for Cognac Expert online shop",
    width: 1468,
    height: 1058,
  },
  {
    imageId: "Illustration_sak92",
    imageTitle:
      "Wärmbert character illustration – a hot water bottle for homeless people during winter",
    imageUrl: "/Images/Illustrations/Waermbert.jpg",
    alt: "Wärmbert character illustration",
    width: 1080,
    height: 798,
  },
  {
    imageId: "Illustration_5jgk2",
    imageTitle: "Illustration of Clean Logistics H2 Truck",
    imageUrl: "/Images/Illustrations/Clean_Logistics_Illustration_1.jpg",
    alt: "Illustration of Clean Logistics H2 Truck",
    width: 1080,
    height: 798,
  },
  {
    imageId: "Illustration_9jgk2",
    imageTitle: "Illustration of Clean Logistics H2 Bus",
    imageUrl: "/Images/Illustrations/Clean_Logistics_Illustration_2.jpg",
    alt: "Illustration of Clean Logistics H2 Bus",
    width: 1084,
    height: 794,
  },
];

export const webDesignImagesData = [
  {
    imageId: "WebDesign_dJ820",
    imageTitle: "Concept design for Herbies Cuisine",
    imageUrl: "/Images/Web_Design/Herbies_Cuisine.jpg",
    alt: "Concept design for Herbies Cuisine",
    width: 1486,
    height: 1200,
  },
  {
    imageId: "WebDesign_bajki",
    imageTitle: "Concept design for Good Talk website",
    imageUrl: "/Images/Web_Design/Goodtalk.jpg",
    alt: "Concept design for Good Talk website",
    width: 1593,
    height: 1200,
  },
  {
    imageId: "WebDesign_as561",
    imageTitle: "Website Design for Schlosser & Partner",
    imageUrl: "/Images/Web_Design/Schlosser_Partner.jpg",
    alt: "Website Design for Schlosser & Partner",
    width: 1599,
    height: 1200,
  },
  {
    imageId: "WebDesign_ak93f",
    imageTitle: "Website design for Phoenix Xtra Blankets",
    imageUrl: "/Images/Web_Design/Phoenix.jpg",
    alt: "Website design for Phoenix Xtra Blankets",
    width: 1588,
    height: 1200,
  },
];

export const printImagesData = [
  {
    imageId: "Print_32rgf",
    imageTitle: "Editorial design of Cognac Expert Magazine",
    imageUrl: "/Images/Print/CE_Magazine_1.jpg",
    alt: "Editorial design of Cognac Expert Magazine",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_10cna",
    imageTitle: "Editorial design of Cognac Expert Magazine",
    imageUrl: "/Images/Print/CE_Magazine_2.jpg",
    alt: "Editorial design of Cognac Expert Magazine",
    width: 1797,
    height: 1200,
  },
  {
    imageId: "Print_aski9",
    imageTitle:
      "Instructional flyer design for Wärmbert – a hot water bottle for homeless people during winter",
    imageUrl: "/Images/Print/Waermbert_Flyer.jpg",
    alt: "Instructional flyer design for Wärmbert",
    width: 1714,
    height: 1045,
  },
  {
    imageId: "Print_sdsdr",
    imageTitle: "Cover design for SO COSI broschure",
    imageUrl: "/Images/Print/SO_COSI_Broschure_1.jpg",
    alt: "Cover design for SO COSI broschure",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_a45m2",
    imageTitle: "SO COSI product broschure design",
    imageUrl: "/Images/Print/SO_COSI_Broschure_2.jpg",
    alt: "SO COSI product broschure design",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_wer23",
    imageTitle: "Rollup banner for POPULAIRE – a cognac & popcorn drink",
    imageUrl: "/Images/Print/Populaire.jpg",
    alt: "Rollup banner for POPULAIRE",
    width: 1330,
    height: 1200,
  },
  {
    imageId: "Print_e0r12",
    imageTitle: "Cover design for Clean Logistics broschure",
    imageUrl: "/Images/Print/Clean_Logistics_Broschure_1.jpg",
    alt: "Cover design for Clean Logistics broschure",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_ihw72",
    imageTitle: "Content pages of Clean Logistics broschure",
    imageUrl: "/Images/Print/Clean_Logistics_Broschure_2.jpg",
    alt: "Content pages of Clean Logistics broschure",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_pb6r1",
    imageTitle: "Stamp card design fot Schwartau team event",
    imageUrl: "/Images/Print/Schwartau_Stempelkarte.jpg",
    alt: "Stamp card design fot Schwartau team event",
    width: 1410,
    height: 1071,
  },
  {
    imageId: "Print_456re",
    imageTitle: "eCap Mobility broschure cover design",
    imageUrl: "/Images/Print/eCap_Broschure_1.jpg",
    alt: "eCap Mobility broschure cover",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_axzo7",
    imageTitle: "eCap Mobility broschure content pages",
    imageUrl: "/Images/Print/eCap_Broschure_2.jpg",
    alt: "eCap Mobility broschure content pages",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_slskl",
    imageTitle: "Schiffbautechnische Gesellschaft broschure cover",
    imageUrl: "/Images/Print/STG_Broschure_1.jpg",
    alt: "Schiffbautechnische Gesellschaft broschure cover",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_attwo",
    imageTitle:
      "Content pages of broschure for Schiffbautechnische Gesellschaft",
    imageUrl: "/Images/Print/STG_Broschure_2.jpg",
    alt: "Content pages of broschure for Schiffbautechnische Gesellschaft",
    width: 1058,
    height: 1200,
  },
];

export const logoImagesData = [
  {
    imageId: "Logos_05jsb",
    imageTitle: "Logo for JN Publishing",
    imageUrl: "/Images/Logos/Logo_JN_Publishing.jpg",
    alt: "Logo for JN Publishing",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_hla3q",
    imageTitle: "Logo for BOX",
    imageUrl: "/Images/Logos/Logo_Box.jpg",
    alt: "Logo for BOX",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_phk23",
    imageTitle: "Logo for Bio Äpfel Altes Land GmbH",
    imageUrl: "/Images/Logos/Logo_Bio_Aepfel.jpg",
    alt: "Logo for BioÄpfel Altes Land GmbH",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_7345l",
    imageTitle: "Logo for Dissonar music events",
    imageUrl: "/Images/Logos/Logo_Dissonar.jpg",
    alt: "Logo for Dissonar music events",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_f086a",
    imageTitle: "Logo for eCap Mobility",
    imageUrl: "/Images/Logos/Logo_eCap.jpg",
    alt: "Logo for eCap Mobility",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_2ii8s",
    imageTitle: "Logo for Elblinien",
    imageUrl: "/Images/Logos/Logo_Elblinien.jpg",
    alt: "Logo for Elblinien",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_l985d",
    imageTitle: "Logo for envise",
    imageUrl: "/Images/Logos/Logo_envise.jpg",
    alt: "Logo for envise",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_q99hd",
    imageTitle: "Logo for Gleitsmann Gebäudeservice",
    imageUrl: "/Images/Logos/Logo_Gleitsmann.jpg",
    alt: "Logo for Gleitsmann Gebäudeservice",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_5zhds",
    imageTitle: "Logo for Herbies Cuisine",
    imageUrl: "/Images/Logos/Logo_Herbies_Cuisine.jpg",
    alt: "Logo for Herbies Cuisine",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_sauiw",
    imageTitle: "Logo for Home of Classics",
    imageUrl: "/Images/Logos/Logo_HOC.jpg",
    alt: "Logo for Home of Classics",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_a0urb",
    imageTitle: "Logo for Hoppe Marine",
    imageUrl: "/Images/Logos/Logo_Hoppe.jpg",
    alt: "Logo for Hoppe Marine",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_wpopb",
    imageTitle: "Logo for Hybrid Port Energy",
    imageUrl: "/Images/Logos/Logo_HPE.jpg",
    alt: "Logo for Hybrid Port Energy",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_wimdh",
    imageTitle: "Logo for MKO Marine Consulting",
    imageUrl: "/Images/Logos/Logo_MKO.jpg",
    alt: "Logo for MKO Marine Consulting",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_2i8sd",
    imageTitle: "Logo for Ocean Grey",
    imageUrl: "/Images/Logos/Logo_Ocean_Grey.jpg",
    alt: "Logo for Ocean Grey",
    width: 1080,
    height: 800,
  },
];

export const packagingImagesData = [
  {
    imageId: "Packaging_skifh",
    imageTitle: "Packaging design for Bio Obst Augustin Hagel-Aepfel",
    imageUrl: "/Images/Packaging/Augustin.jpg",
    alt: "Packaging design for Bio Obst Augustin Hagel-Aepfel",
    width: 1400,
    height: 1200,
  },
  {
    imageId: "Packaging_sdhh7",
    imageTitle: "Label design for L'ESSENTIEL series",
    imageUrl: "/Images/Packaging/L'ESSENTIEL_Bottles.jpg",
    alt: "Label design for L'ESSENTIEL series",
    width: 1698,
    height: 1200,
  },
  {
    imageId: "Packaging_apid9",
    imageTitle: "Label design for OUI VIE",
    imageUrl: "/Images/Packaging/OUI_VIE.jpg",
    alt: "Label design for OUI VIE",
    width: 717,
    height: 1200,
  },
  {
    imageId: "Packaging_38z45",
    imageTitle: "Label design for Populaire",
    imageUrl: "/Images/Packaging/Populaire.jpg",
    alt: "Label design for Populaire",
    width: 1489,
    height: 1200,
  },
  {
    imageId: "Packaging_sbzzj",
    imageTitle: "Label design for vintage cognacs",
    imageUrl: "/Images/Packaging/Vintage_Cognacs.jpg",
    alt: "Label design for vintage cognacs",
    width: 1171,
    height: 1200,
  },
  {
    imageId: "Packaging_222sk",
    imageTitle: "Label design for Cognac Imaginé",
    imageUrl: "/Images/Packaging/Cognac_Imaginé.jpg",
    alt: "Label design for Cognac Imaginé",
    width: 717,
    height: 1200,
  },
];
