export const illustrationImagesData = [
  {
    imageId: "Illustration_39874",
    imageTitle: "GullyGang NFT Header",
    imageUrl: "/Images/Illustrations/GullyGang_Header.png",
    alt: "Image of Gully Beach",
    width: 2133,
    height: 1200,
  },
  {
    imageId: "Illustration_kf948",
    imageTitle: "GullyGang NFT Gull",
    imageUrl: "/Images/Illustrations/GullyGang_Gull_1.png",
    alt: "Image of Gully Gang Gully",
    width: 1200,
    height: 1200,
  },
  {
    imageId: "Illustration_cka72",
    imageTitle: "GullyGang NFT Gull",
    imageUrl: "/Images/Illustrations/GullyGang_Gull_2.png",
    alt: "Image of Gully Gang Gully",
    width: 1200,
    height: 1200,
  },
  {
    imageId: "Illustration_bbre6",
    imageTitle: "GullyGang NFT Gull",
    imageUrl: "/Images/Illustrations/GullyGang_Gull_3.png",
    alt: "Image of Gully Gang Gully",
    width: 1200,
    height: 1200,
  },
  {
    imageId: "Illustration_dho32",
    imageTitle: "GullyGang NFT Gulls",
    imageUrl: "/Images/Illustrations/GullyGang_Group.png",
    alt: "Image of Gully Gang Gullies",
    width: 1800,
    height: 1200,
  },
  {
    imageId: "Illustration_vafg8",
    imageTitle: "Bio Obst Augustin – Hagel Aepfel",
    imageUrl: "/Images/Illustrations/Augustin_Hagel_Aepfel.jpg",
    alt: " Character Illustration for aplle packaging",
    width: 1147,
    height: 943,
  },
  {
    imageId: "Illustration_ftl66",
    imageTitle: "Douglas Wiesn illustrationen",
    imageUrl: "/Images/Illustrations/Douglas_Wiesn_Illustration.jpg",
    alt: "Illustration for Douglas Wiesn invite",
    width: 981,
    height: 987,
  },
  {
    imageId: "Illustration_jlx31",
    imageTitle: "Cognac Expert icons",
    imageUrl: "/Images/Illustrations/CE_Icons.jpg",
    alt: "Icon set for Cognac Expert online shop",
    width: 1468,
    height: 1058,
  },
  {
    imageId: "Illustration_sak92",
    imageTitle: "Wärmbert Character illustration",
    imageUrl: "/Images/Illustrations/Waermbert.jpg",
    alt: "Wärmbert Character illustration",
    width: 1080,
    height: 798,
  },
  {
    imageId: "Illustration_5jgk2",
    imageTitle: "Clean Logistic H2 Truck illustration",
    imageUrl: "/Images/Illustrations/Clean_Logistics_Illustration_1.jpg",
    alt: "Clean Logistic H2 Truck illustration",
    width: 1080,
    height: 798,
  },
  {
    imageId: "Illustration_9jgk2",
    imageTitle: "Clean Logistic H2 Bus illustration",
    imageUrl: "/Images/Illustrations/Clean_Logistics_Illustration_2.jpg",
    alt: "Clean Logistic H2 Bus illustration",
    width: 1084,
    height: 794,
  },
];

export const webDesignImagesData = [
  {
    imageId: "WebDesign_dJ820",
    imageTitle: "Herbies Cuisine website design",
    imageUrl: "/Images/Web_Design/Herbies_Cuisine.jpg",
    alt: "Herbies Cuisine website design",
    width: 1486,
    height: 1200,
  },
  {
    imageId: "WebDesign_bajki",
    imageTitle: "Good Talk website design",
    imageUrl: "/Images/Web_Design/Goodtalk.jpg",
    alt: "Good Talk website design",
    width: 1593,
    height: 1200,
  },
  {
    imageId: "WebDesign_as561",
    imageTitle: "Schlosser & Partner website design",
    imageUrl: "/Images/Web_Design/Schlosser_Partner.jpg",
    alt: "Schlosser & Partner website design",
    width: 1599,
    height: 1200,
  },
  {
    imageId: "WebDesign_ak93f",
    imageTitle: "Phoenix Xtra Blankets website design",
    imageUrl: "/Images/Web_Design/Phoenix.jpg",
    alt: "Phoenix Xtra Blankets website design",
    width: 1588,
    height: 1200,
  },
];

export const printImagesData = [
  {
    imageId: "Print_32rgf",
    imageTitle: "Cognac Expert Magazine cover",
    imageUrl: "/Images/Print/CE_Magazine_1.jpg",
    alt: "Cognac Expert Magazine cover",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_10cna",
    imageTitle: "Cognac Expert Magazine content page",
    imageUrl: "/Images/Print/CE_Magazine_2.jpg",
    alt: "Cognac Expert Magazine content page",
    width: 1797,
    height: 1200,
  },
  {
    imageId: "Print_aski9",
    imageTitle: "Wärmbert flyer",
    imageUrl: "/Images/Print/Waermbert_Flyer.jpg",
    alt: "Wärmbert flyer",
    width: 1714,
    height: 1045,
  },
  {
    imageId: "Print_sdsdr",
    imageTitle: "SO COSI broschure cover",
    imageUrl: "/Images/Print/SO_COSI_Broschure_1.jpg",
    alt: "SO COSI broschure cover",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_a45m2",
    imageTitle: "SO COSI broschure content page",
    imageUrl: "/Images/Print/SO_COSI_Broschure_2.jpg",
    alt: "SO COSI broschure content page",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_wer23",
    imageTitle: "POPULAIRE banner design",
    imageUrl: "/Images/Print/Populaire.jpg",
    alt: "POPULAIRE banner design",
    width: 1330,
    height: 1200,
  },
  {
    imageId: "Print_e0r12",
    imageTitle: "Clean Logistics broschure cover",
    imageUrl: "/Images/Print/Clean_Logistics_Broschure_1.jpg",
    alt: "Clean Logistics broschure cover",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_ihw72",
    imageTitle: "Clean Logistics broschure content pages",
    imageUrl: "/Images/Print/Clean_Logistics_Broschure_2.jpg",
    alt: "Clean Logistics broschure content pages",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_pb6r1",
    imageTitle: "Schwartau stamp card",
    imageUrl: "/Images/Print/Schwartau_Stempelkarte.jpg",
    alt: "Schwartau stamp card",
    width: 1410,
    height: 1071,
  },
  {
    imageId: "Print_456re",
    imageTitle: "eCap Mobility broschure cover",
    imageUrl: "/Images/Print/eCap_Broschure_1.jpg",
    alt: "eCap Mobility broschure cover",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_axzo7",
    imageTitle: "eCap Mobility broschure content pages",
    imageUrl: "/Images/Print/eCap_Broschure_2.jpg",
    alt: "eCap Mobility broschure content pages",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_slskl",
    imageTitle: "Schiffbautechnische Gesellschaft broschure cover",
    imageUrl: "/Images/Print/STG_Broschure_1.jpg",
    alt: "Schiffbautechnische Gesellschaft broschure cover",
    width: 1058,
    height: 1200,
  },
  {
    imageId: "Print_attwo",
    imageTitle: "Schiffbautechnische Gesellschaft broschure content pages",
    imageUrl: "/Images/Print/STG_Broschure_2.jpg",
    alt: "Schiffbautechnische Gesellschaft broschure content pages",
    width: 1058,
    height: 1200,
  },
];

export const logoImagesData = [
  {
    imageId: "Logos_hla3q",
    imageTitle: "Logo design for Box",
    imageUrl: "/Images/Logos/Logo_Box.jpg",
    alt: "Logo design for Box",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_phk23",
    imageTitle: "Logo design for Bio Äpfel Altes Land GmbH",
    imageUrl: "/Images/Logos/Logo_Bio_Aepfel.jpg",
    alt: "Logo design for BioÄpfel Altes Land GmbH",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_7345l",
    imageTitle: "Logo design for Dissonar",
    imageUrl: "/Images/Logos/Logo_Dissonar.jpg",
    alt: "Logo design for Dissonar",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_f086a",
    imageTitle: "Logo design for eCap Mobility",
    imageUrl: "/Images/Logos/Logo_eCap.jpg",
    alt: "Logo design for eCap Mobility",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_2ii8s",
    imageTitle: "Logo design for Elblinien",
    imageUrl: "/Images/Logos/Logo_Elblinien.jpg",
    alt: "Logo design for Elblinien",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_l985d",
    imageTitle: "Logo design for envise",
    imageUrl: "/Images/Logos/Logo_envise.jpg",
    alt: "Logo design for envise",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_q99hd",
    imageTitle: "Logo design for Gleitsmann Gebäudeservice",
    imageUrl: "/Images/Logos/Logo_Gleitsmann.jpg",
    alt: "Logo design for Gleitsmann Gebäudeservice",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_5zhds",
    imageTitle: "Logo design for Herbies Cuisine",
    imageUrl: "/Images/Logos/Logo_Herbies_Cuisine.jpg",
    alt: "Logo design for Herbies Cuisine",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_sauiw",
    imageTitle: "Logo design for Home of Classics",
    imageUrl: "/Images/Logos/Logo_HOC.jpg",
    alt: "Logo design for Home of Classics",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_a0urb",
    imageTitle: "Logo design for Hoppe Marine",
    imageUrl: "/Images/Logos/Logo_Hoppe.jpg",
    alt: "Logo design for Hoppe Marine",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_wpopb",
    imageTitle: "Logo design for Hybrid Port Energy",
    imageUrl: "/Images/Logos/Logo_HPE.jpg",
    alt: "Logo design for Hybrid Port Energy",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_wimdh",
    imageTitle: "Logo design for MKO Marine Consulting",
    imageUrl: "/Images/Logos/Logo_MKO.jpg",
    alt: "Logo design for MKO Marine Consulting",
    width: 1080,
    height: 800,
  },
  {
    imageId: "Logos_2i8sd",
    imageTitle: "Logo design for Ocean Grey",
    imageUrl: "/Images/Logos/Logo_Ocean_Grey.jpg",
    alt: "Logo design for Ocean Grey",
    width: 1080,
    height: 800,
  },
];

export const packagingImagesData = [
  {
    imageId: "Packaging_skifh",
    imageTitle: "Packaging design for Bio Obst Augustin Hagel-Aepfel",
    imageUrl: "/Images/Packaging/Augustin.jpg",
    alt: "Packaging design for Bio Obst Augustin Hagel-Aepfel",
    width: 1400,
    height: 1200,
  },
  {
    imageId: "Packaging_sdhh7",
    imageTitle: "Label design for L'ESSENTIEL series",
    imageUrl: "/Images/Packaging/L'ESSENTIEL_Bottles.jpg",
    alt: "Label design for L'ESSENTIEL series",
    width: 1698,
    height: 1200,
  },
  {
    imageId: "Packaging_apid9",
    imageTitle: "Label design for OUI VIE",
    imageUrl: "/Images/Packaging/OUI_VIE.jpg",
    alt: "Label design for OUI VIE",
    width: 717,
    height: 1200,
  },
  {
    imageId: "Packaging_38z45",
    imageTitle: "Label design for Populaire",
    imageUrl: "/Images/Packaging/Populaire.jpg",
    alt: "Label design for Populaire",
    width: 1489,
    height: 1200,
  },
  {
    imageId: "Packaging_sbzzj",
    imageTitle: "Label design for vintage cognacs",
    imageUrl: "/Images/Packaging/Vintage_Cognacs.jpg",
    alt: "Label design for vintage cognacs",
    width: 1171,
    height: 1200,
  },
  {
    imageId: "Packaging_222sk",
    imageTitle: "Label design for Cognac Imaginé",
    imageUrl: "/Images/Packaging/Cognac_Imaginé.jpg",
    alt: "Label design for Cognac Imaginé",
    width: 717,
    height: 1200,
  },
];
